### ISSUE TITLE
Plugin does not run and exits with error

### ISSUE THREAD

**Issue by AdamBanham** [promworkbench/StochasticWeightEstimation#1]
After downloading the latest nightly build and installing the package, the plugin 'Mine stochastic Petri net with estimators' crashes out before starting any work or returning the GSPN.

Steps to reproduce:
- attempt to run plugin using an event log and a petri net (not the accepting type)
![image](https://github.com/promworkbench/StochasticWeightEstimation/assets/38652037/847a6e42-e205-4d75-aa7f-83d6b683fe32)
- see the error; likely from a configuration problem with some GUI note within
https://github.com/promworkbench/StochasticWeightEstimation/blob/e46b00b3012877817ae257a11da78fa45e00fc38/src/org/processmining/stochasticweightestimation/plugins/EstimatorPluginConfiguration.java#L56-L71
![image (1)](https://github.com/promworkbench/StochasticWeightEstimation/assets/38652037/4be7234e-6d7e-434b-9326-05f28a4a9393)
- crash information in the command line is noted below
- the problem with the plugin may extend from the following line: https://github.com/promworkbench/StochasticWeightEstimation/blob/e46b00b3012877817ae257a11da78fa45e00fc38/src/org/processmining/stochasticweightestimation/plugins/SPDWeightEstimatorPlugin.java#L83

Crash information from command line:
```
Start plug-in Mine Stochastic Petri net with estimators
-------- The following exception was logged by the framework:
         The exception was probalby handled properly.
java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at javax.swing.SwingWorker.get(Unknown Source)
        at org.processmining.framework.plugin.ProMFuture.get(ProMFuture.java:119)
        at org.processmining.framework.plugin.impl.AbstractPluginDescriptor$1.done(AbstractPluginDescriptor.java:187)
        at org.processmining.framework.plugin.ProMFuture$1.done(ProMFuture.java:66)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.processmining.framework.plugin.impl.PluginDescriptorImpl.execute(PluginDescriptorImpl.java:329)
        at org.processmining.framework.plugin.impl.AbstractPluginDescriptor$1.doInBackground(AbstractPluginDescriptor.java:149)
        at org.processmining.framework.plugin.ProMFuture$1.doInBackground(ProMFuture.java:56)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.processmining.stochasticweightestimation.plugins.EstimatorPluginConfiguration
        at org.processmining.stochasticweightestimation.plugins.SPDWeightEstimatorPlugin.mineGUISPNWithEstimator(SPDWeightEstimatorPlugin.java:83)
        ... 13 more
--------------------------------------------------------------
```

**Comment by adamburkegh** [comment]
Hi thanks for the clear bug report. It doesn't reproduce locally when built from source, which suggests some dependency getting lost in the build process. 

FWIW `NoClassDefFoundError`, when it occurs, often shows up in constructors, because that is one of the triggers for class loading. But usually it's not that constructor that has the problem, it's some other class going missing.

If you need an immediate workaround you could checkout the plugin locally.

**Comment by AdamBanham** [comment]
Not in a rush, but some notice when the plugin would work in the nightly build would be nice. 

No one but us (maybe sander and eric as well) is checking out local source mate, if it does not work from the package manager, you are going to miss citations.

**Comment by adamburkegh** [comment]
Yeah well since I was speaking to someone in that elite group I thought I'd mention it

**Comment by adamburkegh** [comment]
More informative stacktrace:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at au.edu.qut.prom.helpers.StochasticPetriNetUtils.<clinit>(StochasticPetriNetUtils.java:28)
        at au.edu.qut.pm.spn_estimator.MeanScaledActivityPairRHEstimator.edgePairWeights(MeanScaledActivityPairRHEstimator.java:39)
        at au.edu.qut.pm.spn_estimator.MeanScaledActivityPairRHEstimator.estimateWeights(MeanScaledActivityPairRHEstimator.java:25)
        at au.edu.qut.pm.spn_estimator.AbstractFrequencyEstimator.estimateWeights(AbstractFrequencyEstimator.java:76)
        at org.processmining.stochasticweightestimation.plugins.SPDWeightEstimatorPlugin.mineSPNFromLogWithEstimator(SPDWeightEstimatorPlugin.java:113)
        at org.processmining.stochasticweightestimation.plugins.SPDWeightEstimatorPlugin.mineSPNFromLogWithDefaults(SPDWeightEstimatorPlugin.java:70)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 19 more

```

ie, the apache log4j classes are misisng.

**Comment by adamburkegh** [comment]
Fixed in https://github.com/promworkbench/StochasticWeightEstimation/commit/4fa9aa7cda56e25a1fc406276e034577967c0d77 .  The new ProM build has some post traumatic stress disorder that reacts to log4j by shooting things, including this plugin. This is probably because of the [Log4Shell](https://en.wikipedia.org/wiki/Log4Shell) vulnerability that caused much upheaval with web-facing applications that used log4j, and impacted the ProM build server. ProM plugins themselves were of course never a vector for the attack.

After trying to convince the ProM build system to stop silently removing it, gave up and ripped log4j out with a chainsaw. Replaced with a thin facade over `System.out.println()`. Works now. Logging in headless mode less informative than it was, no longer logs the source class.

**Comment by adamburkegh** [comment]
Fixed in https://github.com/promworkbench/StochasticWeightEstimation/commit/4fa9aa7cda56e25a1fc406276e034577967c0d77 .  The new ProM build has some post traumatic stress disorder that reacts to log4j by shooting things, including this plugin. This is probably because of the [Log4Shell](https://en.wikipedia.org/wiki/Log4Shell) vulnerability that caused much upheaval with web-facing applications that used log4j, and impacted the ProM build server. ProM plugins themselves were of course never a vector for the attack.

After trying to convince the ProM build system to stop silently removing it, gave up and ripped log4j out with a chainsaw. Replaced with a thin facade over `System.out.println()`. Works now. Logging in headless mode less informative than it was, no longer logs the source class.
